PT-515 Add capacity to display YLP version coming from env
mdblp/health-check pull request #11
Opened 2019-07-30 16:00 UTC by BigFab

Modifications for Health-check before modifications on YourLoops

2019-07-30 16:41 UTC, ydrisR requested changes
Tests are required ;)
* reflect the new signature of the constructor
* add a test in test_service to verify the version of yourloops is returned by the service
* add a test in test_env to verify the new env variable is retrieved as expected by the program

2019-07-30 16:41 UTC, ydrisR commented on service.js
> +    constructor(ylpVersion, services) {
You will need to update the tests to use this new signature, OR to switch both variables

2019-07-31 12:08 UTC, BigFab commented
Existing tests have been fixed and new ones have been added

2019-07-31 12:36 UTC, ydrisR requested changes
Nice improvement :)
A couple of changes (to discuss if you disagree):
1) Either set a default value for env.ylpVersion or throw an error at startup time if the environment variable is null or empty. 
2) Why not return OK or NOK as a status for the yourloops entry instead of 200/503? That would be nice to have the same convention for all services, and even if we know what 200/503 means, OK/NOK is a bit clearer I think.

2019-07-31 12:36 UTC, ydrisR commented on env.js
> +  env.ylpVersion = process.env.YLP_VERSION;
```suggestion
  env.ylpVersion = process.env.YLP_VERSION || "unknown";
```

2019-07-31 12:36 UTC, ydrisR commented on service.js
>                          this.logger.info("all services are up and running!");
```suggestion
                        this.logger.info("all services are up and running!");
                        ylp['status']="OK";
```

2019-07-31 12:36 UTC, ydrisR commented on service.js
> +                        responseStatus = 503;
```suggestion
                        responseStatus = 503;
                        ylp['status'] = "NOK";
```

2019-07-31 12:36 UTC, ydrisR commented on service.js
> +                    ylp['status'] = responseStatus;
```suggestion
```

2019-07-31 12:36 UTC, ydrisR commented on test/test_service.js
> +            statusResults[0].status.should.eql(200);
```suggestion
            statusResults[0].status.should.eql("OK");
```

2019-07-31 12:36 UTC, ydrisR commented on test/test_service.js
> +            statusResults[0].status.should.eql(503);
```suggestion
            statusResults[0].status.should.eql("NOK");
```

2019-07-31 12:38 UTC, ydrisR requested changes

2019-07-31 12:38 UTC, ydrisR commented on CHANGELOG.md
> +## [Unreleased]
```suggestion
## 1.1.0 - 2019-07-31
```

2019-08-01 07:13 UTC, ydrisR requested changes
Almost perfect ;)

2019-08-01 07:13 UTC, ydrisR commented on test/test_service.js
> +                .get('/access/status').reply(200, "OK")
hmm hmm, the double quotes had a purpose ;)

2019-08-01 09:54 UTC, ydrisR approved these changes
🚀 🎆

2019-08-01 13:50 UTC, merged